# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - sachakr-function-app-demo

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.11" # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          venv\Scripts\activate.bat

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: |
          Compress-Archive -Path .\* -DestinationPath release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: Expand-Archive release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Retrieve secrets from Azure Key Vault
        id: get-secrets
        run: |
          echo "Retrieving secrets from Key Vault"
          CLIENT_ID=$(az keyvault secret show --name "AZURE-CLIENT-ID" --vault-name "sachakr-key-vault" --query "value" -o tsv)
          TENANT_ID=$(az keyvault secret show --name "AZURE-TENANT-ID" --vault-name "sachakr-key-vault" --query "value" -o tsv)
          SUBSCRIPTION_ID=$(az keyvault secret show --name "AZURE-SUBSCRIPTION-ID" --vault-name "sachakr-key-vault" --query "value" -o tsv)
          echo "AZURE_CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "AZURE_TENANT_ID=$TENANT_ID" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

      - name: Deploy to Azure Function App
        run: |
          echo "Deploying to Azure with Client ID: ${{ env.AZURE_CLIENT_ID }}"

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: "sachakr-function-app-demo"
          slot-name: "Production"
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
